export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body style={{ backgroundColor: '#0d0d0d', margin: 0 }}>
        {children}
      </body>
    </html>
  )
}